base_url = "https://freddycansick.co.uk/"
compile_sass = true
build_search_index = false
default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "css"
render_emoji = true
smart_punctuation = true

highlight_themes_css = [
  { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
# Put all your custom variables here